# yaml-language-server: $schema=./.kokimoki/schema.json

# Translations
title: 'Red Handed Poker'

gameLobbyMd: |
  # Waiting for game to start...
  The game will start once the host presses the start button.

connectionsMd: |
  # List of players

sharedStateMd: |
  # Shared State example

players: 'Players'
timeElapsed: 'Time elapsed'
startButton: 'Start Game'
stopButton: 'Stop Game'

loading: 'Loading...'

menuTitle: 'Menu'
menuConnections: 'Connections'
menuGameLobby: 'Lobby'

playerNameTitle: 'Enter Your Name'
playerNamePlaceholder: 'Your name...'
playerNameLabel: 'Name:'
playerNameButton: 'Continue'
randomNameButton: 'Random Name'
dontCheatHelpText: 'Be a good boy, don''t cheat. Don''t try to figure out how to cheat.'

hostLabel: 'Host'
presenterLabel: 'Presenter'

gameLinksTitle: 'Game Links'
playerLinkLabel: 'Player Link'
presenterLinkLabel: 'Presenter Link'

menuAriaLabel: 'Open menu drawer'

# Poker-specific
bettingPhaseTitle: 'Betting Phase'
resultsTitle: 'Round Results'
roundNumber: 'Round'
yourCards: 'Your Cards'
yourGold: 'Your Gold'
currentBet: 'Current Bet'
pot: 'Pot'
timeRemaining: 'Time Remaining'

selectCardsToChange: 'Select cards to change (tap to select)'
cardsSelected: 'cards selected'
changeCardsButton: 'Change Cards'
cardsChanged: 'Cards changed! You can now place your bet.'
placeBetButton: 'Place Bet'
foldButton: 'Fold'
allIn: 'ALL IN'

youWon: 'You Won!'
youLost: 'You Lost'
youFolded: 'You Folded'
winnings: 'Winnings'
losses: 'Losses'

rulesTitle: 'RULES'
gameRulesDescription: 'Each round, players receive 5 cards and place bets. At the end of the betting phase, the player with the best hand wins the pot (the sum of all bets).'
handRankingsTitle: 'Poker Hand Rankings'
viewHandRankings: 'Rules'
importantNoteTitle: 'Important Note'
importantNoteText: 'It''s forbidden to cheat. Don''t try to figure out how to cheat. Be a good boy!'

startGameButton: 'Start Game'
endBettingButton: 'End Betting Phase'
newRoundButton: 'Start New Round'
endGameButton: 'End Game'
startNewGameButton: 'Start New Game'

gameOver: 'Game Over'
gameOverMd: 'You ran out of gold! Better luck next time.'
rejoinButton: 'Rejoin Game'

redistributedGoldTitle: 'Bonus Gold'
redistributedGoldMessage: 'You received part of the gold redistributed from caught cheaters!'
foldedNoGoldMessage: 'Cheater(s) were caught and punished. You received nothing because you folded or did not bet.'

denounceCheaters: 'Denounce Cheaters'
denounceExplainer: 'If you suspect one or more players of cheating, use this'
denounceTitle: 'Select Suspected Cheaters'
denounceConfirm: 'Confirm'
denounceCancel: 'Cancel'

botchedCheatingMessage: 'You botched your cheating attempt! You got a duplicate card.'

finalRankingsTitle: 'Final Rankings'
winner: 'Winner'
resetPlayersButton: 'Reset Players'

cheatDiscussionHint: ' Before starting a new round, feel free to discuss with players to determine who might be cheating.'

minimalBetLabel: 'Minimal bet'

startingGold: 100
bettingPhaseDuration: 120000
minimalBet: 1
